apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: pubsub
spec:
  type: pubsub.azure.eventhubs
  version: v1
  metadata:
  - name: namespaceName
    value: "healthcare-eventhub"
  - name: consumerGroup
    value: "$Default"
  - name: connectionString
    secretRef: eventhub-connection
secrets:
- name: eventhub-connection
  key: EventHubConnection