name: Notification Service CI/CD

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'src/NotificationService/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'src/NotificationService/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore src/NotificationService/notificationservice.function/NotificationService.csproj

    - name: Build
      run: dotnet build src/NotificationService/notificationservice.function/NotificationService.csproj --no-restore -c Release

    - name: Publish Function App
      run: dotnet publish src/NotificationService/notificationservice.function/NotificationService.csproj -c Release -o ./publish

    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy to Azure Function App
      uses: Azure/functions-action@v1
      with:
        app-name: healthcare-notification
        package: ./publish
        publish-profile: ${{ secrets.AZURE_FUNCTIONS_PUBLISH_PROFILE }}

    - name: Configure Function App Settings
      uses: azure/CLI@v1
      with:
        inlineScript: |
          az functionapp config appsettings set \
            --name healthcare-notification \
            --resource-group healthcare-rg \
            --settings \
              "ASPNETCORE_ENVIRONMENT=Development" \
              "EventHubConnection=secret://healthcare-vault/EventHubConnection" \
              "APPLICATIONINSIGHTS_CONNECTION_STRING=secret://healthcare-vault/AppInsightsConnection"