name: Notification Service CI/CD

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'src/NotificationService/**'
      - '.github/workflows/ci-cd.notification.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'src/NotificationService/**'
      - '.github/workflows/ci-cd.notification.yml'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore src/NotificationService/notificationservice.function/notificationservice.function.csproj

    - name: Build
      run: dotnet build src/NotificationService/notificationservice.function/notificationservice.function.csproj --no-restore -c Release

    - name: Publish Function App
      run: dotnet publish src/NotificationService/notificationservice.function/notificationservice.function.csproj -c Release -o ./publish

    - name: Login to Azure
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Ensure Development Slot Exists
      uses: azure/CLI@v2
      with:
        inlineScript: |
          az functionapp deployment slot list --name healthcare-notification --resource-group healthcare-rg --query "[?name=='development']" | grep -q development || \
          az functionapp deployment slot create --name healthcare-notification --resource-group healthcare-rg --slot development

    - name: Deploy to Azure Function App
      uses: Azure/functions-action@v1
      with:
        app-name: healthcare-notification
        package: ./publish
        slot-name: development
        credentials: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Configure Function App Settings
      uses: azure/CLI@v2
      with:
        inlineScript: |
          az functionapp config appsettings set \
            --name healthcare-notification \
            --resource-group healthcare-rg \
            --slot development \
            --settings \
              "ASPNETCORE_ENVIRONMENT=Development" \
              "EventHubConnection=secret://healthcare-vault/EventHubConnection" \
              "APPLICATIONINSIGHTS_CONNECTION_STRING=secret://healthcare-vault/AppInsightsConnection"