name: Update APIM Swagger

on:
  workflow_call:
    inputs:
      serviceName:
        required: true
        type: string
      apiVersion:
        required: false
        type: string
        default: 'v1'
      swaggerBlobPath:
        required: false
        type: string
        default: 'swagger-artifacts/${{ inputs.serviceName }}/${{ inputs.apiVersion }}/swagger.json'
      storageAccountName:
        required: false
        type: string
        default: 'healthcarergb9d7'
      apimResourceGroup:
        required: false
        type: string
        default: 'healthcare-rg'
      apimServiceName:
        required: false
        type: string
        default: 'healthcare-apim'
      azureCredentials:
        required: true
        type: string

jobs:
  update-apim-swagger:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ inputs.azureCredentials }}

      - name: Download Swagger from Blob Storage
        run: |
          az storage blob download \
            --account-name ${{ inputs.storageAccountName }} \
            --container-name swagger-artifacts \
            --name ${{ inputs.serviceName }}/${{ inputs.apiVersion }}/swagger.json \
            --file swagger.json \
            --auth-mode login
        continue-on-error: false

      - name: Validate Swagger JSON
        run: |
          jq . swagger.json > /dev/null || { echo "Invalid Swagger JSON"; exit 1; }
          echo "Swagger JSON is valid"

      - name: Update Swagger in APIM
        run: |
          az apim api import \
            --resource-group ${{ inputs.apimResourceGroup }} \
            --service-name ${{ inputs.apimServiceName }} \
            --api-id ${{ inputs.serviceName }}-${{ inputs.apiVersion }} \
            --path /${{ inputs.serviceName }}/${{ inputs.apiVersion }} \
            --specification-format OpenApi \
            --specification-path swagger.json \
            --api-type http
          echo "Successfully updated APIM API for ${{ inputs.serviceName }}-${{ inputs.apiVersion }}"
        continue-on-error: false