name: Appointment Service CI/CD

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'src/AppointmentService/**'
      - '.github/workflows/ci-cd.appointment.yml'
      - '.github/workflows/ci-cd.auth.yml'
      - '.github/workflows/ci-cd.notification.yml'
      - 'dapr/components/pubsub.yaml'
  pull_request:
    branches: [ main ]
    paths:
      - 'src/AppointmentService/**'
      - '.github/workflows/ci-cd.appointment.yml'
      - '.github/workflows/ci-cd.auth.yml'
      - '.github/workflows/ci-cd.notification.yml'
      - 'dapr/components/pubsub.yaml'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore src/AppointmentService/appointment.api/appointment.api.csproj

    - name: Build
      run: dotnet build src/AppointmentService/appointment.api/appointment.api.csproj --no-restore -c Release

    - name: Login to Azure
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Login to Azure Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ secrets.ACR_REGISTRY }}
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v6
      with:
        context: .
        file: src/AppointmentService/appointment.api/Dockerfile
        push: true
        tags: |
          ${{ secrets.ACR_REGISTRY }}/appointment-service:${{ github.sha }}
          ${{ secrets.ACR_REGISTRY }}/appointment-service:latest
        platforms: linux/amd64

    - name: Apply Dapr Components
      uses: azure/CLI@v2
      with:
        inlineScript: |
          az containerapp env dapr-component set \
            --dapr-component-name pubsub \
            --environment healthcare-ca-env \
            --resource-group healthcare-rg \
            --yaml ./dapr/components/pubsub.yaml

    - name: Deploy to Azure Container App
      uses: azure/CLI@v2
      with:
        inlineScript: |
          az containerapp create \
            --name appointment-service \
            --resource-group healthcare-rg \
            --environment healthcare-ca-env \
            --image ${{ secrets.ACR_REGISTRY }}/appointment-service:${{ github.sha }} \
            --target-port 8080 \
            --ingress external \
            --registry-server ${{ secrets.ACR_REGISTRY }} \
            --registry-username ${{ secrets.ACR_USERNAME }} \
            --registry-password ${{ secrets.ACR_PASSWORD }} \
            --user-assigned healthcare-identity \
            --cpu 0.5 \
            --memory 1.0Gi \
            --min-replicas 1 \
            --max-replicas 3 \
            --enable-dapr \
            --dapr-app-id appointment-service \
            --dapr-app-port 8080 \
            --env-vars \
              "ASPNETCORE_ENVIRONMENT=Development" \
              "KeyVault__VaultUri=https://healthcare-vault.vault.azure.net/" \
              "ConnectionStrings__SqlConnection=secret://healthcare-vault/SqlConnection" \
              "AppConfiguration__ConnectionString=secret://healthcare-vault/AppConfigConnection" \
              "Jwt__Key=secret://healthcare-vault/JwtKey" \
              "Jwt__Issuer=HealthcareAuthService" \
              "Jwt__Audience=HealthcareApi" \
              "ApplicationInsights__ConnectionString=secret://healthcare-vault/AppInsightsConnection" \
              "Dapr__PubSubName=pubsub"