name: Flyway Migrations

on:
  push:
    branches:
      - main
    paths:
      - 'src/FlywayMigrations/**' # Trigger only on changes to migration scripts
      - '.github/workflows/flyway-migration.yml' # Trigger on workflow changes
  pull_request:
    branches:
      - main
    paths:
      - 'src/FlywayMigrations/**'
      - '.github/workflows/flyway-migration.yml'

jobs:
  migrate:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Install Flyway CLI 11.8.2 with retry and error handling
      - name: Install Flyway
        run: |
          mkdir -p flyway
          for i in {1..3}; do
            echo "Attempt $i to download Flyway CLI 11.8.2"
            if wget -qO flyway.tar.gz https://repo1.maven.org/maven2/org/flywaydb/flyway-commandline/11.8.2/flyway-commandline-11.8.2-linux-x64.tar.gz; then
              tar -xzf flyway.tar.gz -C flyway --strip-components=1
              break
            else
              echo "Download failed, retrying in 5 seconds..."
              sleep 5
            fi
          done
          if [ ! -f flyway/flyway ]; then
            echo "Failed to download or extract Flyway CLI after 3 attempts"
            exit 1
          fi
          sudo mv flyway /usr/local/flyway
          sudo chmod +x /usr/local/flyway/flyway
        shell: bash

      # Verify configuration
      - name: Verify Configuration
        run: |
          if [ -z "$AZURE_SP_CLIENT_ID" ]; then
            echo "ERROR: AZURE_SP_CLIENT_ID is not set"
            exit 1
          fi
          if [ -z "$AZURE_CLIENT_SECRET" ]; then
            echo "ERROR: AZURE_CLIENT_SECRET is not set"
            exit 1
          fi
          if [ -z "$AZURE_TENANT_ID" ]; then
            echo "ERROR: AZURE_TENANT_ID is not set"
            exit 1
          fi
          if [ ! -f "flyway.conf" ]; then
            echo "ERROR: flyway.conf not found in repository root"
            exit 1
          else
            echo "flyway.conf found at $(pwd)/flyway.conf"
            cat flyway.conf
          fi
        env:
          AZURE_SP_CLIENT_ID: ${{ secrets.AZURE_SP_CLIENT_ID }}
          AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

      # Run Flyway migrations using flyway.conf
      - name: Run Flyway Migrations
        run: |
          /usr/local/flyway/flyway \
            -configFiles="flyway.conf" \
            -locations="filesystem:src/FlywayMigrations" \
            -X \
            migrate
        env:
          AZURE_SP_CLIENT_ID: ${{ secrets.AZURE_SP_CLIENT_ID }}
          AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}