name: Flyway Migrations and Container App Deployment

on:
  push:
    branches:
      - main
    paths:
      - 'src/FlywayMigrations/**' # Trigger only on changes to this folder
      - '.github/workflows/flyway-migration.yml'
  pull_request:
    branches:
      - main
    paths:
      - 'src/FlywayMigrations/**'
      - '.github/workflows/flyway-migration.yml'

jobs:
  migrate-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up .NET (if needed for your app build)
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      # Install Flyway CLI
      - name: Install Flyway
        run: |
          wget -qO- https://repo1.maven.org/maven2/org/flywaydb/flyway-commandline/11.9.1/flyway-commandline-11.9.1-linux-x64.tar.gz | tar xvz
          sudo mv flyway-11.9.1 /usr/local/flyway
          sudo chmod +x /usr/local/flyway/flyway

      # Run Flyway migrations
      - name: Run Flyway Migrations
        run: |
          /usr/local/flyway/flyway \
            -url="jdbc:sqlserver://healthcare-sql.database.windows.net:1433;database=HealthcareDB;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;authentication=ActiveDirectoryManagedIdentity" \
            -locations="filesystem:src/FlywayMigrations" \
            -schemas="healthcare" \
            -connectRetries=5 \
            -connectRetriesInterval=10 \
            migrate
        env:
          AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}